import type { Metadata } from 'next';
import './globals.css';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import DataAosProvider from '@/components/DataAosProvider';

export const metadata: Metadata = {
  title: 'BrandNasu',
  description: 'Generated by create next app',
  icons: {
    icon: [{ url: '/faveicon.svg', type: 'image/svg+xml' }],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" sizes="any" />
      </head>
      <body className="bg-gray100">
        <Navbar />
        <DataAosProvider>{children}</DataAosProvider>
        <Footer />
      </body>
    </html>
  );
}
