import type { Metadata } from 'next';
import './globals.css';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import DataAosProvider from '@/components/DataAosProvider';

export const metadata: Metadata = {
  title: 'BrandNasu Real State',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray100">
        <Navbar />
        <DataAosProvider>{children}</DataAosProvider>
        <Footer />
      </body>
    </html>
  );
}
